#Get sightings in a location

GET http://localhost:3000/sightings
Content-Type: application/json

{
  "location": "L161180"
}

###

#Find Locations in a State
GET http://localhost:3000/locations
Content-Type: application/json

{
  "state": "IL"
}

###
#Get a list of hotspots in a region
GET http://localhost:3000/hotspots/
Content-Type: application/json

{
  "region": "US-IL-031"
}

### Gets all sightings within 2 hours of the entered time at a location
GET http://localhost:3000/time
Content-Type: application/json

{
  "year": "2021",
  "month": "04",
  "day": "01",
  "hour": "14",
  "minute": "30",
  "location": "L161180"
}

###
#Takes a user date and pulls all historic bird observation data for the week before and the week after

GET http://localhost:3000/historic
Content-Type: application/json

{
  "hotspot": "L161180",
  "year": "2021",
  "month": "04",
  "day": "01"
}

### takes a user date and pulls historic bird observation data for the week before and the week after, and SHOULD return sightings that occured within 1 hour before or after the entered time

GET http://localhost:3000/historic-time
Content-Type: application/json

{
  "hotspot": "L161180",
  "year": "2021",
  "month": "04",
  "day": "01",
  "hour": "07",
  "minute": "00"
}

###

GET http://localhost:3000/bird
Content-Type: application/json

{
  "speciesCode": "gockin"
}